In [1]:
'''
【课程2.2】  Pandas数据结构Series：基本概念及创建
​
"一维数组"Serise
​
'''

'\n【课程2.2】  Pandas数据结构Series：基本概念及创建\n\u200b\n"一维数组"Serise\n\u200b\n'

In [4]:
import numpy as np
import pandas as pd
ar = np.random.random(5)
s1 = s = pd.Series(ar)  
s = pd.Series(ar,index = list('abcde'))  #index可以改变索引的值
print(ar)
print(s)
print(s1)
print(type(s))
print('-------------')
print(s.index)
print(s.values[2])
print(s.index[2])
# .index查看series索引，类型为rangeindex
# .values查看series值，类型是ndarray
#series相当于是有序的字典

# 核心：series相比于ndarray，是一个自带索引index的数组 → 一维数组 + 对应索引
# 所以当只看series的值的时候，就是一个ndarray
# series和ndarray较相似，索引切片功能差别不大
# series和dict相比，series更像一个有顺序的字典（dict本身不存在顺序），其索引原理与字典相似（一个用key，一个用index）

[ 0.82118173  0.65983853  0.68579358  0.37092049  0.88041514]
a    0.821182
b    0.659839
c    0.685794
d    0.370920
e    0.880415
dtype: float64
0    0.821182
1    0.659839
2    0.685794
3    0.370920
4    0.880415
dtype: float64
<class 'pandas.core.series.Series'>
-------------
Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
0.68579357814
c


In [4]:
#Series的创建 这是由字典创建的
dic = {'a':1,'b':2,'c':3}
s = pd.Series(dic)
print(s)

a    1
b    2
c    3
dtype: int64


In [15]:
#由一维数组创建
ar = np.random.random(5)*100
s = pd.Series(ar)
print(s)
s1 = pd.Series(ar,index = list('abcde'),dtype= np.object) #bojict和str一样是字符型
print(s1)

0    47.611232
1    45.309880
2    78.949866
3    25.459442
4     7.436362
dtype: float64
a    47.6112
b    45.3099
c    78.9499
d    25.4594
e    7.43636
dtype: object


In [17]:
#由标量创建
s = pd.Series(10,index=range(5))
print(s)

0    10
1    10
2    10
3    10
4    10
dtype: int64


In [24]:
#Series的名称属性name
s1 = pd.Series(np.random.random(5))
print(s1)
s2 = pd.Series(np.random.random(5),name='test')
print(s2)
print(s1.name)
# name为Series的一个参数，创建一个数组的 名称
# .name方法：输出数组的名称，输出格式为str，如果没用定义输出名称，输出为None

#重命名rename
s3 = s2.rename('niniupi')
print(s3)
print(s2)
# .rename()重命名一个数组的名称，并且新指向一个数组，原数组不变

0    0.033202
1    0.590485
2    0.802642
3    0.075950
4    0.462768
dtype: float64
0    0.192665
1    0.201051
2    0.718924
3    0.212547
4    0.171197
Name: test, dtype: float64
None
0    0.192665
1    0.201051
2    0.718924
3    0.212547
4    0.171197
Name: niniupi, dtype: float64
0    0.192665
1    0.201051
2    0.718924
3    0.212547
4    0.171197
Name: test, dtype: float64


In [8]:
#作业练习
import numpy as np
ar = np.arange(25,dtype= np.float32).reshape(5,5)
print(ar)
ar[:2,:2] = np.random.rand(2,2)
print(ar)
ar1 = np.random.rand(4,2)
print(ar1)

b = np.random.normal(size=(2,2))
print(b)
data = np.random.normal(size=(2,10))
print(data)

c = np.random.randint(0,100,size=(10,10))
print(c)
np.savetxt('wotoyanni.txt',c,delimiter=',')
print('finished')

[[  0.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.]
 [ 15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.]]
[[  0.50943756   0.26958293   2.           3.           4.        ]
 [  0.32886752   0.78878367   7.           8.           9.        ]
 [ 10.          11.          12.          13.          14.        ]
 [ 15.          16.          17.          18.          19.        ]
 [ 20.          21.          22.          23.          24.        ]]
[[ 0.13719734  0.73320446]
 [ 0.45385868  0.81747992]
 [ 0.00740996  0.08749528]
 [ 0.89697333  0.87965017]]
[[ 1.18632207  0.65327614]
 [-0.94596821  1.00194402]]
[[-1.23158886  0.813921   -0.77102414 -1.24381839 -1.03480237 -0.55249238
   0.35327443 -0.49991951 -0.69481585 -0.330254  ]
 [ 0.58425833  1.47966261  1.9903692  -0.29165301 -0.33301859 -0.76645143
   0.66266375  0.48477913 -0.85109609 -0.79817768]]
[[75 70 69 44 23 50 44 56 86 46]
 [63 32 27 22 69 44 32 87 78 13]
 [14 71 26 23 42 51 96 39 41 61]
 [28

In [23]:
#作业练习
import pandas as pd
dic = {'jack':96,'chenglong':25,'chenqiaoen':20}
print(dic)
s1 = pd.Series(dic,name='作业1')
print(s1)
ar = np.array([36,25,23])
print(ar)
s2 = pd.Series(ar,name= '作业1',dtype = np.float64,index= ['jacl','chenglong','feilipu'])
print(s2)

{'chenqiaoen': 20, 'jack': 96, 'chenglong': 25}
chenglong     25
chenqiaoen    20
jack          96
Name: 作业1, dtype: int64
[36 25 23]
jacl         36.0
chenglong    25.0
feilipu      23.0
Name: 作业1, dtype: float64


In [73]:
#作业练习
ar = np.random.rand(10)*100
print(ar)
s1 = pd.Series(ar,index= ['a','b','c','d','e','f','g','h','i','j'])
print(s1)
print('--------')
print(s1['b'])
print(s1[['a','b']])  #取多个值
print('----------')
print(s1[4:7])
print(s1[s1.values>50])

[ 88.35836035  66.04809568   2.29504569  17.1330316   59.5346069
  78.67235422  67.5458375   29.94435544  39.10575187  82.22266415]
a    88.358360
b    66.048096
c     2.295046
d    17.133032
e    59.534607
f    78.672354
g    67.545838
h    29.944355
i    39.105752
j    82.222664
dtype: float64
--------
66.0480956807
a    88.358360
b    66.048096
dtype: float64
----------
e    59.534607
f    78.672354
g    67.545838
dtype: float64
a    88.358360
b    66.048096
e    59.534607
f    78.672354
g    67.545838
j    82.222664
dtype: float64


In [70]:
s1 = pd.Series(np.array(range(10)),index=list('abcdefghij'))
print(s1)
s1['a'] = 100
print(s1)

SyntaxError: invalid syntax (<ipython-input-70-671f2296d887>, line 3)

In [74]:
s1 = pd.Series(np.random.rand(5)*10,index=list('abcde'))
print(s1)
s2 = pd.Series(np.random.rand(5)*10,index=list('abcde'))
print(s2)
print(s1+s2)

a    2.197295
b    4.499850
c    5.940777
d    3.354403
e    7.215687
dtype: float64
a    6.335967
b    8.440667
c    3.330514
d    8.496300
e    7.468795
dtype: float64
a     8.533262
b    12.940518
c     9.271291
d    11.850703
e    14.684482
dtype: float64


In [75]:
'''
【课程2.3】  Pandas数据结构Series：索引

位置下标 / 标签索引 / 切片索引 / 布尔型索引

'''

'\n【课程2.3】  Pandas数据结构Series：索引\n\n位置下标 / 标签索引 / 切片索引 / 布尔型索引\n\n'

In [76]:
# 位置下标，类似序列

s = pd.Series(np.random.rand(5))
print(s)
print(s[0],type(s[0]),s[0].dtype)
print(float(s[0]),type(float(s[0])))
#print(s[-1])
# 位置下标从0开始
# 输出结果为numpy.float格式，
# 可以通过float()函数转换为python float格式
# numpy.float与float占用字节不同
# s[-1]结果如何？

0    0.682719
1    0.747006
2    0.837560
3    0.379276
4    0.985096
dtype: float64
0.682718738412 <class 'numpy.float64'> float64
0.6827187384118202 <class 'float'>


In [5]:
# 标签索引

s = pd.Series(np.random.rand(5), index = ['a','b','c','d','e'])
print(s)
print(s['a'],type(s['a']),s['a'].dtype)
print(s.values.dtype)
# 方法类似下标索引，用[]表示，内写上index，注意index是字符串

sci = s[['a','b','e']]
print(sci,type(sci))
# 如果需要选择多个标签的值，用[[]]来表示（相当于[]中包含一个列表）
# 多标签索引结果是新的数组

a    0.649258
b    0.683256
c    0.306273
d    0.388808
e    0.493551
dtype: float64
0.649257583856 <class 'numpy.float64'> float64
float64
a    0.649258
b    0.683256
e    0.493551
dtype: float64 <class 'pandas.core.series.Series'>


In [79]:
# 切片索引

s1 = pd.Series(np.random.rand(5))
s2 = pd.Series(np.random.rand(5), index = ['a','b','c','d','e'])
print(s1[1:4],s1[4])
print(s2['a':'c'],s2['c'])
print(s2[0:3],s2[3])
print('-----')
# 注意：用index做切片是末端包含

print(s2[:-1])
print(s2[::2])
# 下标索引做切片，和list写法一样

1    0.758515
2    0.276289
3    0.355082
dtype: float64 0.0178253271135
a    0.554780
b    0.455895
c    0.354254
dtype: float64 0.354253922236
a    0.554780
b    0.455895
c    0.354254
dtype: float64 0.171215401091
-----
a    0.554780
b    0.455895
c    0.354254
d    0.171215
dtype: float64
a    0.554780
c    0.354254
e    0.956725
dtype: float64


In [18]:
# 布尔型索引

s = pd.Series(np.random.rand(3)*100)
df = pd.DataFrame(np.random.rand(3,3))
s[4] = None  # 添加一个空值
print(s)
bs1 = s > 50
bs2 = s.isnull()
bs3 = s.notnull()
print(bs1, type(bs1), bs1.dtype)
print(bs2, type(bs2), bs2.dtype)
print(bs3, type(bs3), bs3.dtype)
print('-----')
# 数组做判断之后，返回的是一个由布尔值组成的新的数组
# .isnull() / .notnull() 判断是否为空值 (None代表空值，NaN代表有问题的数值，两个都会识别为空值)

print(s[s > 50])
print(s[bs3])

df[2][2] = None


# 布尔型索引方法：用[判断条件]表示，其中判断条件可以是 一个语句，或者是 一个布尔型数组！

0    74.9844
1    30.4337
2    58.6967
4       None
dtype: object
0     True
1    False
2     True
4    False
dtype: bool <class 'pandas.core.series.Series'> bool
0    False
1    False
2    False
4     True
dtype: bool <class 'pandas.core.series.Series'> bool
0     True
1     True
2     True
4    False
dtype: bool <class 'pandas.core.series.Series'> bool
-----
0    74.9844
2    58.6967
dtype: object
0    74.9844
1    30.4337
2    58.6967
dtype: object
Empty DataFrame
Columns: [0, 1, 2]
Index: []


In [90]:
s = pd.Series(np.array(range(10)))
print(s)
s[3] = 100
print(s)
s[11] = 0
psd = s.notnull()
print(psd)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32
0      0
1      1
2      2
3    100
4      4
5      5
6      6
7      7
8      8
9      9
dtype: int32
0     True
1     True
2     True
3     True
4     True
5     True
6     True
7     True
8     True
9     True
11    True
dtype: bool


In [96]:
#数据查看
s = pd.Series(np.random.rand(10))
print(s.head(4))  #默认是查看前5条数据和后五条数据
print(s.tail())

0    0.625319
1    0.777063
2    0.872813
3    0.259643
dtype: float64
5    0.927953
6    0.277820
7    0.590982
8    0.626623
9    0.361195
dtype: float64


In [20]:
#改编索引的顺序
s = pd.Series(np.random.rand(5),index=list('abcde'))
s1 = s.reindex(['c','d','e','a','f'])
print(s)
print(s1)
s2 = s.reindex(['c','b','a','g'], fill_value = 4) #没有的指默认填充为0
print(s2)

a    0.945796
b    0.153253
c    0.629957
d    0.404712
e    0.302164
dtype: float64
c    0.629957
d    0.404712
e    0.302164
a    0.945796
f         NaN
dtype: float64
c    0.629957
b    0.153253
a    0.945796
g    4.000000
dtype: float64


In [104]:
#对齐

s1 = pd.Series(np.random.rand(3), index = ['Jack','Marry','Tom'])
s2 = pd.Series(np.random.rand(3), index = ['Wang','Jack','Marry'])
print(s1+s2)

Jack     1.563137
Marry    1.525819
Tom           NaN
Wang          NaN
dtype: float64


In [43]:
#删除drop
s = pd.Series(np.array(range(5)),index= list('abcde'))
print(s)

print(s.drop('a'))
#print(s.drop(['a','d']) )#删除多个元素
# drop 删除元素之后返回副本(inplace=False)
#print(s.drop('b',inplace=True))
#print(s)  #尽管不返回副本，但元素已经被删除
lst = [1,2,3]
lst.pop(1)
print(lst)

a    0
b    1
c    2
d    3
e    4
dtype: int32
b    1
c    2
d    3
e    4
dtype: int32
[1, 3]


In [22]:
#添加
s = pd.Series(np.array(range(4)),index= list('abcd'))
s['f'] = 89
print(s)
s1 = pd.Series(np.array(range(3)))
s2 = s.append(s1)
print(s2)
print(s)  #append不改变原来数组的值


a     0
b     1
c     2
d     3
f    89
dtype: int64
a     0
b     1
c     2
d     3
f    89
0     0
1     1
2     2
dtype: int64
a     0
b     1
c     2
d     3
f    89
dtype: int64


In [126]:
'''
【课程2.5】  Pandas数据结构Dataframe：基本概念及创建

"二维数组"Dataframe：是一个表格型的数据结构，包含一组有序的列，其列的值类型可以是数值、字符串、布尔值等。

Dataframe中的数据以一个或多个二维块存放，不是列表、字典或一维数组结构。

'''

'\n【课程2.5】  Pandas数据结构Dataframe：基本概念及创建\n\n"二维数组"Dataframe：是一个表格型的数据结构，包含一组有序的列，其列的值类型可以是数值、字符串、布尔值等。\n\nDataframe中的数据以一个或多个二维块存放，不是列表、字典或一维数组结构。\n\n'

In [2]:
 #Dataframe     #dataframe 的创建,由字典和数组可以创建
import pandas as pd 
import numpy as np
data1 = {'jack':['我喜欢你','你个蠢猪'],'chenlong':['我爱你','你是智障吗'],'liuyifei':['你是我的一切','抱得紧紧的']}
data2 = {'dad':np.random.rand(3),
        'mom':np.random.rand(3)}
frame = pd.DataFrame(data1)  
fm2 = pd.DataFrame(data2)
# columns参数：可以重新指定列的顺序，格式为list，如果现有数据中没有该列（比如'd'），则产生NaN值
# 如果columns重新指定时候，列的数量可以少于原数据
print(frame)
print(fm2)
print('-----------')
print(type(frame))
print(frame.index)
print(frame.values)
print(frame.columns)
# .index查看行标签
# .columns查看列标签
# .values查看值，数据类型为ndarray
print('----------')
print(frame['jack'][0])

  chenlong  jack liuyifei
0      我爱你  我喜欢你   你是我的一切
1    你是智障吗  你个蠢猪    抱得紧紧的
        dad       mom
0  0.956666  0.601843
1  0.332659  0.549954
2  0.317233  0.756073
-----------
<class 'pandas.core.frame.DataFrame'>
RangeIndex(start=0, stop=2, step=1)
[['我爱你' '我喜欢你' '你是我的一切']
 ['你是智障吗' '你个蠢猪' '抱得紧紧的']]
Index(['chenlong', 'jack', 'liuyifei'], dtype='object')
----------
我喜欢你


In [165]:
#dataframe 的创建方法3：由series构成的字典创建
data1 = {'one':pd.Series(np.random.rand(3),index = list('abc')),
        'two':pd.Series(np.random.rand(2)),
        'three':pd.Series(np.random.rand(2))}
data2 = {'one':pd.Series(np.random.rand(3)),
        'two':pd.Series(np.random.rand(2)),
        'three':pd.Series(np.random.rand(2))}
print(data1)
fm1 = pd.DataFrame(data1)
fm2 = pd.DataFrame(data2)

print(fm1)
print(fm1+fm2)
# 由Seris组成的字典 创建Dataframe，columns为字典key，index为Series的标签（如果Series没有指定标签，则是默认数字标签）
# Series可以长度不一样，生成的Dataframe会出现NaN值

{'two': 0    0.521648
1    0.144938
dtype: float64, 'one': a    0.113609
b    0.441961
c    0.758809
dtype: float64, 'three': 0    0.912586
1    0.018677
dtype: float64}
        one     three       two
a  0.113609       NaN       NaN
b  0.441961       NaN       NaN
c  0.758809       NaN       NaN
0       NaN  0.912586  0.521648
1       NaN  0.018677  0.144938
   one     three       two
a  NaN       NaN       NaN
b  NaN       NaN       NaN
c  NaN       NaN       NaN
0  NaN  1.808640  0.884203
1  NaN  0.746497  0.278932
2  NaN       NaN       NaN


C:\Users\acer\Anaconda3\lib\site-packages\pandas\indexes\api.py:71: RuntimeWarning: unorderable types: int() > str(), sort order is undefined for incomparable objects
  result = result.union(other)
C:\Users\acer\Anaconda3\lib\site-packages\pandas\indexes\base.py:2482: RuntimeWarning: unorderable types: str() < int(), sort order is undefined for incomparable objects
  return this.join(other, how=how, return_indexers=return_indexers)


In [169]:
#dataframe 的创建方法3：通过二维数组直接创建
ar = np.arange(8).reshape(2,4)
print(ar)
df1 = pd.DataFrame(ar)
df2 = pd.DataFrame(ar,index= list('ab'),columns=['one','two','three','four'])
print(df1)
print(df2)

[[0 1 2 3]
 [4 5 6 7]]
   0  1  2  3
0  0  1  2  3
1  4  5  6  7
   one  two  three  four
a    0    1      2     3
b    4    5      6     7


In [181]:
# Dataframe 创建方法四：由字典组成的列表
data1 = [{'one':1,'two':2},{'一':11,'二':22}]
data2 = [{'one':1,'two':2},{'one':11,'two':22,'three':33},{'one':1,'two':2}]
pf1 = pd.DataFrame(data1,index= list('ab'))
pf3 = pd.DataFrame(data1,columns=['one','two'])
pf2 = pd.DataFrame(data2)
print(pf1)
print(pf2)
print(pf3)

   one  two     一     二
a  1.0  2.0   NaN   NaN
b  NaN  NaN  11.0  22.0
   one  three  two
0    1    NaN    2
1   11   33.0   22
2    1    NaN    2
   one  two
0  1.0  2.0
1  NaN  NaN


In [191]:
# Dataframe 创建方法五：由字典组成的字典
data = {'baba':{'mama':65,'baba':70},
       'mama':{'mama':64,'baba':72},
       'ganba':{'mama':66,'baba':71,'zuzong':90}}
df1 = pd.DataFrame(data)
df2 = pd.DataFrame(data,index=['baba','mama'])
df3 = pd.DataFrame(data,columns = ['baba','mama'])
print(df1)
print(df2)
print(df3)
# columns参数可以增加和减少现有列，如出现新的列，值为NaN
# index在这里和之前不同，并不能改变原有index，如果指向新的标签，值为NaN （非常重要！）


        baba  ganba  mama
baba    70.0     71  72.0
mama    65.0     66  64.0
zuzong   NaN     90   NaN
      baba  ganba  mama
baba    70     71    72
mama    65     66    64
      baba  mama
baba    70    72
mama    65    64


In [239]:
#作业练习
ar = np.arange(20).reshape(5,4)
pf1 = pd.DataFrame(ar,index=[list('abcde')],columns=['one','two','three','four'])
print(pf1)

dic1 = {'one':np.random.randint(0,10,size=(5)),
      'two':np.random.randint(0,10,size=(5)),
      'three':np.random.randint(0,10,size=(5)),
      'four':np.random.randint(0,10,size=(5))}
pf2 = pd.DataFrame(dic1,index=list('abcde'),columns = ['one','two','three','four'])
print(pf2)

dic2 = {'one':pd.Series(np.random.randint(0,10,size=(5)),index=list('abcde' )),
       'two':pd.Series(np.random.randint(0,10,size=(5)),index=list('abcde')),
       'three':pd.Series(np.random.randint(0,10,size=(5)),index=list('abcde')),
       'four':pd.Series(np.random.randint(0,10,size=(5)),index=list('abcde'))}
pf3 = pd.DataFrame(dic2,columns = ['one','two','three','four'])
print(pf3)

dic3 = {'one':{'a':np.random.randint(0,10),'b':np.random.randint(0,10),'c':np.random.randint(0,10),'d':np.random.randint(0,10),'e':np.random.randint(0,10)},
       'two':{'a':np.random.randint(0,10),'b':np.random.randint(0,10),'c':np.random.randint(0,10),'d':np.random.randint(0,10),'e':np.random.randint(0,10)},
       'three':{'a':np.random.randint(0,10),'b':np.random.randint(0,10),'c':np.random.randint(0,10),'d':np.random.randint(0,10),'e':np.random.randint(0,10)},
       'four':{'a':np.random.randint(0,10),'b':np.random.randint(0,10),'c':np.random.randint(0,10),'d':np.random.randint(0,10),'e':np.random.randint(0,10)}}
pf4 = pd.DataFrame(dic3,columns = ['one','two','three','four'])
print(pf4)

   one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15
e   16   17     18    19
   one  two  three  four
a    7    1      7     3
b    0    9      8     5
c    5    9      2     4
d    6    1      9     0
e    0    0      9     0
   one  two  three  four
a    9    3      9     2
b    3    1      2     4
c    9    0      4     7
d    5    2      5     5
e    1    0      4     0
   one  two  three  four
a    8    7      9     7
b    3    2      0     4
c    7    6      5     0
d    1    6      7     3
e    9    4      0     5


In [240]:
'''
【课程2.6】  Pandas数据结构Dataframe：索引

Dataframe既有行索引也有列索引，可以被看做由Series组成的字典（共用一个索引）

选择列 / 选择行 / 切片 / 布尔判断

'''

'\n【课程2.6】  Pandas数据结构Dataframe：索引\n\nDataframe既有行索引也有列索引，可以被看做由Series组成的字典（共用一个索引）\n\n选择列 / 选择行 / 切片 / 布尔判断\n\n'

In [10]:
ar = np.arange(20).reshape(5,4)
pf1 = pd.DataFrame(ar,index=list('abcde'),columns=['one','two','three','four'])
print(pf1)

dic1 = {'one':np.random.randint(0,10,size=(5)),
      'two':np.random.randint(0,10,size=(5)),
      'three':np.random.randint(0,10,size=(5)),
      'four':np.random.randint(0,10,size=(5))}
print(pf1['one'])
print(pf1[['one','two']]) #选择一列或多列 

#选择一行与多行
print('======')

print(pf1.loc['a'])
print(pf1.loc[['a','b']])
#或者
print(pf1[1:3])  #这是切片，这是不包含末端的
print(pf1['a':'c']) #这是包含末端的
#或者     # df.iloc[] - 按照整数位置（从轴的0到length-1）选择行
          # 类似list的索引，其顺序就是dataframe的整数位置，从0开始计
print(pf1.iloc[1])  #这个可以改变位置,且不包含末端
print(pf1.iloc[1:3])      #相当于切片
print(pf1.iloc[[1,2]])  #选取多行


   one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
d   12   13     14    15
e   16   17     18    19
a     0
b     4
c     8
d    12
e    16
Name: one, dtype: int32
   one  two
a    0    1
b    4    5
c    8    9
d   12   13
e   16   17
one      0
two      1
three    2
four     3
Name: a, dtype: int32
   one  two  three  four
a    0    1      2     3
b    4    5      6     7
   one  two  three  four
b    4    5      6     7
c    8    9     10    11
   one  two  three  four
a    0    1      2     3
b    4    5      6     7
c    8    9     10    11
one      4
two      5
three    6
four     7
Name: b, dtype: int32
   one  two  three  four
b    4    5      6     7
c    8    9     10    11
   one  two  three  four
b    4    5      6     7
c    8    9     10    11


In [2]:
# 布尔型索引
# 和Series原理相同

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   index = ['one','two','three','four'],
                   columns = ['a','b','c','d'])
print(df)
print('------')

b1 = df < 20
print(b1,type(b1))
print(df[b1])  # 也可以书写为 df[df < 20]
print('------')
# 不做索引则会对数据每个值进行判断
# 索引结果保留 所有数据：True返回原数据，False返回值为NaN

b2 = df['a'] > 50
print(b2,type(b2))
print(df[b2])  # 也可以书写为 df[df['a'] > 50]
print('------')
# 单列做判断
# 索引结果保留 单列判断为True的行数据，包括其他列

b3 = df[['a','b']] > 50
print(b3,type(b3))
print(df[b3])  # 也可以书写为 df[df[['a','b']] > 50]
print('------')
# 多列做判断
# 索引结果保留 所有数据：True返回原数据，False返回值为NaN

b4 = df.loc[['one','three']] < 50
print(b4,type(b4))
print(df[b4])  # 也可以书写为 df[df.loc[['one','three']] < 50]
print('------')
# 多行做判断
# 索引结果保留 所有数据：True返回原数据，False返回值为NaN

NameError: name 'pd' is not defined

In [3]:
'''
【课程2.7】  Pandas数据结构Dataframe：基本技巧

数据查看、转置 / 添加、修改、删除值 / 对齐 / 排序

'''

'\n【课程2.7】  Pandas数据结构Dataframe：基本技巧\n\n数据查看、转置 / 添加、修改、删除值 / 对齐 / 排序\n\n'

In [4]:
# 数据查看、转置

df = pd.DataFrame(np.random.rand(16).reshape(8,2)*100,
                   columns = ['a','b'])
print(df.head(2))
print(df.tail())
# .head()查看头部数据
# .tail()查看尾部数据
# 默认查看5条

print(df.T)
# .T 转置

NameError: name 'pd' is not defined

In [12]:
# 添加与修改
import numpy as np
import pandas as pd
df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   columns = ['a','b','c','d'])
print(df)

df['e'] = 10
df.loc[4] = 20
print(df)
print(df.loc[3])
# 新增列/行并赋值

df['e'] = 20
df[['a','c']] = 100
df[::2] = 0
print(df)
# 索引后直接修改值

           a          b          c          d
a  63.941843  25.061291   4.724942  41.928676
b  75.002829  68.820596  22.789043  53.386266
c  78.057644   2.166814   1.923832  84.156236
d  31.381027  51.234448  28.881459   6.395789
           a          b          c          d   e
a  63.941843  25.061291   4.724942  41.928676  10
b  75.002829  68.820596  22.789043  53.386266  10
c  78.057644   2.166814   1.923832  84.156236  10
d  31.381027  51.234448  28.881459   6.395789  10
4  20.000000  20.000000  20.000000  20.000000  20


KeyError: 'the label [3] is not in the [index]'

In [10]:
# 删除  del / drop()

df = pd.DataFrame(np.random.rand(16).reshape(4,4)*100,
                   columns = ['a','b','c','d'])
print(df)

del df['a']
print(df)
print('-----')
# del语句 - 删除列

print(df.drop(0))
print(df.drop([1,2]))
print(df)
print('-----')
# drop()删除行，inplace=False → 删除后生成新的数据，不改变原数据

print(df.drop(['d'], axis = 1))
print(df)
# drop()删除列，需要加上axis = 1，inplace=False → 删除后生成新的数据，不改变原数据

           a          b          c          d
0  28.535166  40.094422  35.310341  38.008062
1  17.445300  68.454456  25.802988  90.964079
2  97.788838  32.767026  28.804989   5.341845
3  65.346573  29.122564  30.514834  75.937575
           b          c          d
0  40.094422  35.310341  38.008062
1  68.454456  25.802988  90.964079
2  32.767026  28.804989   5.341845
3  29.122564  30.514834  75.937575
-----
           b          c          d
1  68.454456  25.802988  90.964079
2  32.767026  28.804989   5.341845
3  29.122564  30.514834  75.937575
           b          c          d
0  40.094422  35.310341  38.008062
3  29.122564  30.514834  75.937575
           b          c          d
0  40.094422  35.310341  38.008062
1  68.454456  25.802988  90.964079
2  32.767026  28.804989   5.341845
3  29.122564  30.514834  75.937575
-----
           b          c
0  40.094422  35.310341
1  68.454456  25.802988
2  32.767026  28.804989
3  29.122564  30.514834
           b          c          d
0  40.09

In [11]:
# 对齐

df1 = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
df2 = pd.DataFrame(np.random.randn(7, 3), columns=['A', 'B', 'C'])
print(df1 + df2)
# DataFrame对象之间的数据自动按照列和索引（行标签）对齐

          A         B         C   D
0 -0.400455 -0.798336  1.369951 NaN
1  0.062672 -1.214835 -0.882269 NaN
2 -0.163055  0.662585 -0.152514 NaN
3  0.420854 -0.138625 -1.227493 NaN
4 -1.443248  1.503339  0.047669 NaN
5  0.511070 -0.344377 -1.979235 NaN
6  1.388248  0.270481 -0.234690 NaN
7       NaN       NaN       NaN NaN
8       NaN       NaN       NaN NaN
9       NaN       NaN       NaN NaN


In [21]:
# 排序1 - 按值排序 .sort_values
# 同样适用于Series

df1 = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
print(df1)
print(df1.sort_values(['A','B'],ascending=True))
print(df1.sort_values(['A'],ascending=False))

          A         B         C         D
0 -0.398849 -1.495857 -0.948081 -0.426844
1 -1.793312  0.799292  0.157642  0.440157
2 -0.043338  0.929031  0.444776  0.686872
3 -0.232101 -1.813374 -1.086849  0.325252
4 -0.567069 -1.337579  1.006305  0.304746
5  0.949668  1.035446 -0.029933  1.622006
6 -1.160249 -0.465055  0.324351  0.162004
7 -0.496499  1.891986  1.171475 -0.601119
8 -0.178059  0.069039 -0.246183 -1.297734
9  2.178468  0.408917 -1.103873 -0.790460
          A         B         C         D
1 -1.793312  0.799292  0.157642  0.440157
6 -1.160249 -0.465055  0.324351  0.162004
4 -0.567069 -1.337579  1.006305  0.304746
7 -0.496499  1.891986  1.171475 -0.601119
0 -0.398849 -1.495857 -0.948081 -0.426844
3 -0.232101 -1.813374 -1.086849  0.325252
8 -0.178059  0.069039 -0.246183 -1.297734
2 -0.043338  0.929031  0.444776  0.686872
5  0.949668  1.035446 -0.029933  1.622006
9  2.178468  0.408917 -1.103873 -0.790460
          A         B         C         D
9  2.178468  0.408917 -1.103873 -0

In [26]:
# 排序2 - 索引排序 .sort_index
df1 = pd.DataFrame(np.random.randn(10, 4), columns=['A', 'B', 'C', 'D'])
print(df1)
print(df1.sort_index(ascending=False))
print(df2.sort_index())
# 按照index排序
# 默认 ascending=True, inplace=False

          A         B         C         D
0 -0.448933 -1.823191  0.508472  0.125222
1  1.023602  0.935806 -0.718096 -1.326809
2 -1.798650  1.674404  0.827021 -1.243169
3  1.485465  2.172014 -0.952071  0.333610
4 -0.817791 -1.592043  1.269557  0.444030
5 -2.597341 -1.424101 -0.360134  0.558290
6 -0.107562  2.011638 -1.788832 -0.007846
7  0.980349 -0.228642  1.034415  0.073309
8  0.250462 -1.427855 -1.203530  0.848757
9 -0.455517  0.159418 -0.156121  0.825747
          A         B         C         D
9 -0.455517  0.159418 -0.156121  0.825747
8  0.250462 -1.427855 -1.203530  0.848757
7  0.980349 -0.228642  1.034415  0.073309
6 -0.107562  2.011638 -1.788832 -0.007846
5 -2.597341 -1.424101 -0.360134  0.558290
4 -0.817791 -1.592043  1.269557  0.444030
3  1.485465  2.172014 -0.952071  0.333610
2 -1.798650  1.674404  0.827021 -1.243169
1  1.023602  0.935806 -0.718096 -1.326809
0 -0.448933 -1.823191  0.508472  0.125222
          A         B         C
0 -0.852949 -1.657107  0.761250
1  0.736091 

In [43]:
#作业练习
pf1 = pd.DataFrame(np.random.rand(3,3)*100,index=list('abc'),columns=['v1','v2','v3'])
print(pf1)
print(pf1.sort_values(['v1']))
print(pf1.sort_values(['v1'],ascending=False))
print(pf1.sort_index(ascending=False))

pf2 = pd.DataFrame(np.random.rand(5,2)*100,index=list('abcde'),columns=['v1','v2'])
print(pf2)
pf3 = pf2.drop(4)
print(pf3)
#pf3 = pf2.T
#print(pf3)
#del pf3['e']
#print(pf3)

          v1         v2         v3
a  47.161902  49.145175  46.329099
b   3.691876  59.990759   7.102138
c   8.980543  68.576167  80.902349
          v1         v2         v3
b   3.691876  59.990759   7.102138
c   8.980543  68.576167  80.902349
a  47.161902  49.145175  46.329099
          v1         v2         v3
a  47.161902  49.145175  46.329099
c   8.980543  68.576167  80.902349
b   3.691876  59.990759   7.102138
          v1         v2         v3
c   8.980543  68.576167  80.902349
b   3.691876  59.990759   7.102138
a  47.161902  49.145175  46.329099
          v1         v2
a  17.262532  87.708216
b  68.462949   0.214973
c  94.408555  44.160787
d  85.755839  36.198224
e  63.987479  93.070221


ValueError: labels [4] not contained in axis